apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  namespace: user
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/user/health
spec:
  type: NodePort
  selector:
    app: user-api
    module: user
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 32001
